import { Metadata } from 'next';
import TheHeader from './components/TheHeader/TheHeader';
import './global.css'
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Next learning prj',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TheHeader />
        {children}
      </body>
    </html>
  );
}
